easy_admin:
    entities:
        # List the entity class name you want to manage
        - App\Entity\Comment
        - App\Entity\User
        - App\Entity\Like
        - App\Entity\Event
        - App\Entity\Reporting
        - App\Entity\Project
        - App\Entity\ProjectType
