language: php
php:
  - 7.1.9
sudo: true

services:
  - mysql
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

cache:
  directories:
    - $HOME/.composer/cache/files
    - ./bin/.phpunit

env:
  global:
    - APP_ENV=test

matrix:
  fast_finish: true
  include:
    - php: 7.1.18
    - php: 7.2
    - php: 7.3
    - php: nightly
  allow_failures:
    - php: nightly

before_install:
  - '[[ "$TRAVIS_PHP_VERSION" == "nightly" ]] || phpenv config-rm xdebug.ini'
  - composer self-update
  - mysql -e 'CREATE DATABASE IF NOT EXISTS keinosity_test;'
#    init jwt private SSH keys
  - mkdir config/jwt
  - openssl genrsa -out config/jwt/private.pem -aes256 4096 <<< 'pass'
  - openssl rsa -pubout -in config/jwt/private.pem -out config/jwt/public.pem

install:
  - composer install
  - php bin/console doctrine:schema:create --no-interaction
  - php bin/phpunit install

script:
  - php bin/console app:initApp true
  - php bin/phpunit
  # this checks that the YAML config files contain no syntax errors
  - php bin/console lint:yaml config
  # this checks that the Twig template files contain no syntax errors
  - php bin/console lint:twig templates
  # this checks that the XLIFF translations contain no syntax errors
  - php bin/console lint:xliff translations
  # this checks that Doctrine's mapping configurations are valid
  - php bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction
